=== jaburjak/chords/specification/chord-1.dtd
<!ELEMENT chord (name, def)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT def (((def-strings, def-frets) | (def-frets, def-strings)), (def-note | def-mark)*)>
<!ELEMENT def-strings (#PCDATA)>
<!ELEMENT def-frets (#PCDATA)>

<!ELEMENT def-note ((note-string, note-fret) | (note-fret, note-string))>
<!ELEMENT note-string (#PCDATA)>
<!ELEMENT note-fret (#PCDATA)>

<!ELEMENT def-mark ((mark-string, mark-type) | (mark-type, mark-string))>
<!ELEMENT mark-string (#PCDATA)>
<!ELEMENT mark-type (#PCDATA)>

=== jaburjak/chords/specification/examples/chords/Dmi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chord PUBLIC "-//JABURJAK//DTD Chord 1.0//EN" "https://chords.jaburjak.cz/dtd/chord-1.dtd">
<chord>
	<name>Dmi</name>
	<def>
		<def-strings>6</def-strings>
		<def-frets>5</def-frets>
		<def-note>
			<note-string>6</note-string> <!-- left to right, starts with 1 -->
			<note-fret>1</note-fret> <!-- top to bottom, starts with 1 -->
		</def-note>
		<def-note>
			<note-string>4</note-string>
			<note-fret>2</note-fret>
		</def-note>
		<def-note>
			<note-string>5</note-string>
			<note-fret>3</note-fret>
		</def-note>
		<def-mark>
			<mark-string>1</mark-string>
			<mark-type>muted</mark-type>
		</def-mark>
		<def-mark>
			<mark-string>2</mark-string>
			<mark-type>muted</mark-type>
		</def-mark>
		<def-mark>
			<mark-string>3</mark-string>
			<mark-type>open</mark-type>
		</def-mark>
	</def>
</chord>

=== jaburjak/chords/example/C.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chord PUBLIC "-//JABURJAK//DTD Chord 1.0//EN" "https://chords.jaburjak.cz/dtd/chord-1.dtd">
<chord xmlns="https://chords.jaburjak.cz/schema/chord-1.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="https://chords.jaburjak.cz/schema/chord-1.xsd">
	<name>C</name>
	<alt-names>
		<name>Cdur</name>
		<name>Cmajor</name>
	</alt-names>
	<def>
		<def-strings>6</def-strings>
		<def-frets offset="7">12</def-frets>
		<def-note>
			<note-string>6</note-string>
			<note-fret>8</note-fret>
		</def-note>
		<def-note>
			<note-string>5</note-string>
			<note-fret>8</note-fret>
		</def-note>
		<def-note>
			<note-string>4</note-string>
			<note-fret>9</note-fret>
		</def-note>
		<def-note>
			<note-string>3</note-string>
			<note-fret>10</note-fret>
		</def-note>
		<def-mark>
			<mark-string>1</mark-string>
			<mark-type>muted</mark-type>
		</def-mark>
		<def-mark>
			<mark-string>2</mark-string>
			<mark-type>muted</mark-type>
		</def-mark>
	</def>
</chord>

=== jaburjak/chords/specification/examples/chords/F.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chord PUBLIC "-//JABURJAK//DTD Chord 1.0//EN" "https://chords.jaburjak.cz/dtd/chord-1.dtd">
<chord xmlns="https://chords.jaburjak.cz/schema/chord-1.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="https://chords.jaburjak.cz/schema/chord-1.xsd">
	<name>F</name>
	<def>
		<def-strings>6</def-strings>
		<def-frets>5</def-frets>
		<def-note>
			<note-string>1</note-string>
			<note-string>6</note-string>
			<note-fret>1</note-fret>
		</def-note>
		<def-note>
			<note-string>4</note-string>
			<note-fret>2</note-fret>
		</def-note>
		<def-note>
			<note-string>2</note-string>
			<note-fret>3</note-fret>
		</def-note>
		<def-note>
			<note-string>3</note-string>
			<note-fret>3</note-fret>
		</def-note>
	</def>
</chord>
